name: Release
on:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - 'src/**'
  #     - 'ios/**'
  #     - 'android/**'
  #     - 'app.plugin.json'
  #     - 'package.json'
  #     - 'yarn.lock'
  #     - '*.podspec'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: yarn test --maxWorkers=2 --coverage

  build-release:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepare

      - name: Set NPM token & GitHub config
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          git config user.name "Kuatsu CI/CD"
          git config user.email "null@kuatsu.de"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.CICD_PAT }}
